[project]
name = "cma-es"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "matplotlib-inline>=0.1.7",
    "numpy>=2.3.1",
    "seaborn>=0.13.2",
]
